<?php
/**
 * @file
 * Implements functionalities for lamuzette.be
 */


function lamuzette_init() {

}

function lamuzette_menu_alter(&$items) {
  $items['admin/config/development/performance']['access callback'] = '_accesscheck';
}

function _accesscheck(){
  global $user;
  if(in_array('shop admin', $user->roles) || in_array('administrator', $user->roles)){
     return TRUE;
  }
  return FALSE;
}