<?php
/**
 * @file
 * Implements functionalities for lamuzette.be
 */


function lamuzette_menu_alter(&$items) {
  $items['admin/config/development/performance']['access callback'] = '_accesscheck';
}

function _accesscheck(){
  global $user;
  if(in_array('shop admin', $user->roles) || in_array('administrator', $user->roles)){
     return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_action_info.
 * @return type
 */
function lamuzette_rules_action_info() {

  $action = array(
    'lamuzette_calculate_rate_by_order_weight' => array(
      'group' => 'Commerce Shipping',
      'label' => t('Calculate rate by order weight'),
      'provides' => array(
        'order' => array('type' => 'commerce_order', 'label' => t('The order object.')),
      ),
      'parameter' => array(
        'order' => array('type' => 'commerce_order', 'label' => t('The order object.')),
      ),
    )
  );
  return $action;
}

function lamuzette_calculate_rate_by_order_weight($order_id) {

}
